require 'rake'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = 'test/*_spec.rb'
  spec.rspec_opts = ['--backtrace', '-c', '-f d']
end


task :default  => :spec